/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as PresentationIndexRouteImport } from './routes/presentation/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainPresenterRouteImport } from './routes/(main)/presenter'
import { Route as mainLicensesRouteImport } from './routes/(main)/licenses'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationIndexRoute = PresentationIndexRouteImport.update({
  id: '/presentation/',
  path: '/presentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPresenterRoute = mainPresenterRouteImport.update({
  id: '/presenter',
  path: '/presenter',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLicensesRoute = mainLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/licenses': typeof mainLicensesRoute
  '/presenter': typeof mainPresenterRoute
  '/': typeof mainIndexRoute
  '/presentation': typeof PresentationIndexRoute
}
export interface FileRoutesByTo {
  '/licenses': typeof mainLicensesRoute
  '/presenter': typeof mainPresenterRoute
  '/': typeof mainIndexRoute
  '/presentation': typeof PresentationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/licenses': typeof mainLicensesRoute
  '/(main)/presenter': typeof mainPresenterRoute
  '/(main)/': typeof mainIndexRoute
  '/presentation/': typeof PresentationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/licenses' | '/presenter' | '/' | '/presentation'
  fileRoutesByTo: FileRoutesByTo
  to: '/licenses' | '/presenter' | '/' | '/presentation'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/licenses'
    | '/(main)/presenter'
    | '/(main)/'
    | '/presentation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  PresentationIndexRoute: typeof PresentationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation/': {
      id: '/presentation/'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/presenter': {
      id: '/(main)/presenter'
      path: '/presenter'
      fullPath: '/presenter'
      preLoaderRoute: typeof mainPresenterRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/licenses': {
      id: '/(main)/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof mainLicensesRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainLicensesRoute: typeof mainLicensesRoute
  mainPresenterRoute: typeof mainPresenterRoute
  mainIndexRoute: typeof mainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainLicensesRoute: mainLicensesRoute,
  mainPresenterRoute: mainPresenterRoute,
  mainIndexRoute: mainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  PresentationIndexRoute: PresentationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
